Update mirrorlist-update-arch

diff --git a/mirrorlist-update-arch b/mirrorlist-update-arch
--- a/mirrorlist-update-arch
+++ b/mirrorlist-update-arch
@@ -40,14 +40,19 @@ valid_hosts=0
 failed_hosts=0
 response=()
 
-printf '%s\033[s' "Checking each host, please wait ($tmp_file)..."
+printf '%s\033[s' "Checking each host..."
 while IFS= read -r
 do
-    ((count_lines++))
+    # update valid/failed hosts count during processing
+    (( count_lines >= 1 )) && {
+        printf '\033[u\033[s%s' " $valid_hosts/$failed_hosts" >&2
+    }
+
+    (( count_lines++ ))
 
     # "Header" used to validate input lines
     [[ $REPLY == '## Arch Linux repository mirrorlist'* || $REPLY == '## Filtered by'* || $REPLY == '## Generated on'* ]] && {
-        ((flag_header_found++))
+        (( flag_header_found++ ))
         if [[ $REPLY == '## Generated on'* ]]
         then
             printf '%s %s %s\n' "$REPLY" "at $(date '+%T')" "by ${0//*'/'}"
@@ -59,12 +64,12 @@ do
 
     # Ignore these servers
     [[ $REPLY == *'zxcvfdsa.com'* ]] && {
-        failed_hosts=$((failed_hosts+1))
+        (( failed_hosts++ ))
         continue
     }
 
-    #[ "$flag_header_found" -ge 1 ] && {
     [[ $flag_header_found -ge 1 && $REPLY == '#Server'* ]] && {
+
         # Un-comment the host line
         REPLY=${REPLY/#'#Server'/Server}
 
@@ -72,13 +77,15 @@ do
         host_name=${REPLY#*://}
         host_name=${host_name%%/*}
 
+        # use curl to get a round trip time and http code response from the host
+        # and save the results in an array
         # shellcheck disable=SC2207
         IFS=' ' response=( $(curl -s --connect-timeout "$connect_timeout" -m "$max_time" -w "%{time_total} %{http_code}" "https://${host_name}" -o /dev/null 2>/dev/null) )
-        #printf '%s responded %s in %ss\n' "$host_name" "${response[1]}" "${response[0]}" >&2
+        #printf '%s responded %s in %ss\n' "$host_name" "${response[1]}" "${response[0]}" >&2 # NOTE: not compatible with live count update
 
         if (( response[1] >= 400 || ! response[1] ))
         then
-            ((failed_hosts++))
+            (( failed_hosts++ ))
             printf '%s\n' "# $host_name returned http code ${response[1]} in ${response[0]}s"
             continue
         elif (( response[1] <= 400 ))
@@ -86,14 +93,13 @@ do
             # Ignore hosts with round trips times greater than
             if (( $(bc <<< "${response[0]} > 0.650") ))
             then
-                ((failed_hosts++))
+                (( failed_hosts++ ))
             else
-                ((valid_hosts++))
+                (( valid_hosts++ ))
                 printf '%s\n' "$REPLY"
             fi
         fi
     }
-    printf '\033[u\033[s%s' " $valid_hosts/$failed_hosts" >&2
 done < <(curl -sL "$mirrorlist_url" 2>/dev/null) > "$tmp_file"
 
 # If at least one host is found and all three "headers" were found (validate the response)
